import { nanoid } from "nanoid";
import { randFileName, randFirstName, randRecentDate } from "@ngneat/falso";

import { TypeEnum } from "../models";

export const FAKE_TREE_DATA = [
  {
    id: nanoid(),
    name: randFileName(),
    size: "1MB",
    date: randRecentDate(),
    type: TypeEnum.file,
    children: [],
  },
  {
    id: nanoid(),
    name: randFileName(),
    size: "12KB",
    date: randRecentDate(),
    type: TypeEnum.file,
    children: [],
  },
  {
    id: nanoid(),
    name: randFirstName(),
    children: [
      {
        id: nanoid(),
        name: "Folder1", //randFirstName(),
        size: "1MB",
        date: randRecentDate(),
        type: TypeEnum.folder,
        children: [
          {
            id: nanoid(),
            name: randFileName(),
            size: "1GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "12GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "123GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "456GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
        ],
      },
      {
        id: nanoid(),
        name: "Folder2", //randFirstName(),
        size: "10MB",
        date: randRecentDate(),
        type: TypeEnum.folder,
        children: [
          {
            id: nanoid(),
            name: randFileName(),
            size: "1GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "12GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "123GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "456GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
        ],
      },
      {
        id: nanoid(),
        name: "Folder3", //randFirstName(),
        size: "100MB",
        date: randRecentDate(),
        type: TypeEnum.folder,
        children: [
          {
            id: nanoid(),
            name: randFileName(),
            size: "1GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "12GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "123GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
          {
            id: nanoid(),
            name: randFileName(),
            size: "456GB",
            date: randRecentDate(),
            type: TypeEnum.file,
            children: [],
          },
        ],
      },
    ],
    date: randRecentDate(),
    type: TypeEnum.folder,
    size: "789MB",
  },
  {
    id: nanoid(),
    name: randFirstName(),
    children: [
      {
        id: nanoid(),
        name: randFileName(),
        size: "1KB",
        date: randRecentDate(),
        type: TypeEnum.file,
        children: [],
      },
      {
        id: nanoid(),
        name: randFileName(),
        size: "12KB",
        date: randRecentDate(),
        type: TypeEnum.file,
        children: [],
      },
      {
        id: nanoid(),
        name: randFileName(),
        size: "123KB",
        date: randRecentDate(),
        type: TypeEnum.file,
        children: [],
      },
    ],
    date: randRecentDate(),
    type: TypeEnum.folder,
    size: "123MB",
  },
];
